## .travis.yml
#
# https://travis-ci.org
#
# https://github.com/fabic/llvm-clang
#
# ex. https://github.com/rubinius/rubinius/blob/master/.travis.yml

sudo: false

language: cpp

compiler:
#- g++
- clang

os:
- linux
#- osx

branches:
  only:
  - master
  - "/^v\\d+\\./"

env:
  global:
  - LANG="en_US.UTF-8"

# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release" ENABLE_HTTPS="ON" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release" ENABLE_HTTPS="OFF" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="OFF" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release" ENABLE_HTTPS="ON" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release" ENABLE_HTTPS="OFF" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="OFF" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES
# # Support the sanitizers in clang only
# # - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" CMAKE_CXX_FLAGS="-fsanitize=thread"
# # - BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" CMAKE_CXX_FLAGS="-fsanitize=address"
# # TODO(deanberris): It seems Boost is not msan-clean yet; report bugs and maybe fix?
# #- BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" CMAKE_CXX_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins=2"
# # matrix:
# #   exclude:
# #     - compiler: g++
# #       env: BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" CMAKE_CXX_FLAGS="-fsanitize=thread"
# #     - compiler: g++
# #       env: BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" CMAKE_CXX_FLAGS="-fsanitize=address"
# # TODO(deanberris): It seems Boost is not msan-clean yet; report bugs and maybe fix?
# #    - compiler: g++
# #      env: BOOST_VER=1.59.0 BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug" ENABLE_HTTPS="ON" CMAKE_CXX_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins=2"

before_install:
- echo LANG=$LANG
- echo LC_ALL=$LC_ALL
- echo CC=$CC CXX=$CXX
- echo PATH=$PATH
- type -p clang
- type -p clang++
- uname -a

install:
- mkdir -p ${HOME}/bin
- if [ "${CC}" = "gcc" ]; then export TOOLSET="gcc"; ln -s `which g++-4.8` ${HOME}/bin/g++;
  ln -s `which gcc-4.8` ${HOME}/bin/gcc; fi
- if [ "${CC}" = "clang" ]; then export TOOLSET="clang"; ln -s `which clang-3.6` ${HOME}/bin/clang;
  ln -s `which clang++-3.6` ${HOME}/bin/clang++; fi
- export BOOST_VERSION=${BOOST_VER//./_}
- export PATH=${HOME}/bin:${PATH}
- travis_wait ./install-boost.sh
- export BOOST_ROOT=${HOME}/${CC}-boost_${BOOST_VER//./_}
- "${CXX} --version"

# cache:
#   directories:
#   - "${HOME}/${CC}-boost_${BOOST_VER//./_}"

# before_script:
# - travis_retry bundle
# - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config=llvm-config-3.6; fi
# - if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure; fi

script:
- pwd
- ls -l
- source environment-clang.sh
- ./install-gnu-binutils.sh

after_success:
- echo "SUCCESS (after_success)"
- find local/ -type f -ls
# - if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build_support.sh archive_core; fi
# - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then ./scripts/deploy.sh release github website triggers; fi

after_failure:
#- cat build/Testing/Temporary/LastTest.log
- echo "FAILED (after_failure)"
- pwd
- ls -la

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - kalakris-cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - clang-3.6
    - cmake

# notifications:
#   slack:
#     secure: Y7lLjqZ83+b/jaJ5+EKwvgCDeERi4bVbDn9tLp8sieTdu+ENsPI+JmLYSXZXPpe7JrItrXW6uJJXN2wG1h7au4mpVVTghd31HBzuzrqVxDphWPhp16NYzvbAgQQRBXvFVvfSdW/Kb/n2fX6xDApY0t6vNREb/GKg0GyzESb4ZjU=

# notifications:
#   email: false
#   irc:
#     channels:
#     - chat.freenode.net#rubinius
#     template:
#     - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
#   webhooks:
#     urls:
#       secure: h2oTAbAZF6+c6iv/kHoDGtl1mzQDF2vQSKWnO1pwfEz+L80lX9u3+JB+jsbYUcZ9smBRnRRghqxpLBmyzH3QZCrBdxKnTWfGc7I7lkTCFQZ5O3pPmIusO6W5zX+YUc+NHPPZXouHuHFmEeEB9vJnt/YB/fyGAGOIq+qXV4s+R9M=
#     on_success: always
#     on_failure: always
#     on_start: always
